# Generated by Django 3.2 on 2021-04-19 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Task Text')),
                ('is_complited', models.BooleanField(default=False, verbose_name='Is Task Complited')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time when Task was created')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who created task')),
            ],
        ),
    ]
